- apps/admin-web/src/app/app.spec.tsx
- apps/admin-web/src/app/app.tsx
- apps/admin-web/src/app/components/RouteItem.tsx
- apps/admin-web/src/app/utils/urlHelper.ts
- apps/admin-web/src/app/utils/useSort.ts
- libs/core/package.json
- libs/core/src/index.ts
- libs/interfaces/package.json
- libs/interfaces/src/lib/interfaces.ts
- Add icon showing sort order
- Resolve TS issue
- Use a filter over sort
> Mezzo UI enhancements

- libs/core/src/index.ts
- libs/core/src/lib/core.ts
- libs/core/src/utils/logger.ts
> Add suppot for setLogLevel

- libs/core/src/lib/__tests__/redirect.spec.ts
- libs/core/src/lib/core.ts
- libs/core/src/lib/redirect.ts
- libs/core/src/utils/curry.ts
> Add redirect support

- libs/core/src/index.ts
- libs/core/src/lib/core.ts
> Support global variants

- libs/core/src/lib/__tests__/route-express.spec.ts
- libs/core/src/lib/__tests__/route-file-io.spec.ts
- libs/core/src/types.ts
- libs/core/src/utils/common-utils.ts
- libs/core/src/utils/filePathUtils.ts
> Add more complex dynamic route example

- apps/admin-web/src/app/components/RouteItem.tsx
Noticed my mouse didn't have a pointer when I hovered a route, added the pointer style
Before
https://user-images.githubusercontent.com/16733681/164915118-ec8bf20f-3d1f-4774-8e60-75edead14ed0.mov
After
https://user-images.githubusercontent.com/16733681/164915122-a2f43288-35fe-451f-98d9-73c11d69d5c9.mov
> Routes should change cursor to pointer on hover

- libs/constants/src/lib/constants.ts
- libs/core/src/lib/core.ts
- libs/core/src/types.ts
> Support non localhost connection for set/update/reset variant

- apps/admin-web/src/app/app.tsx
- apps/admin-web/src/app/components/RouteItem.tsx
- libs/core/src/index.ts
- package-lock.json
- package.json
Routes list should animate when we search something
Current animation:
https://user-images.githubusercontent.com/16733681/164987576-679bd5b8-2845-4984-9b35-7a169178d0eb.mp4
As an alternative, staggered animation works with a single prop change, but I thought the animation was too distracting if you have a long list
https://user-images.githubusercontent.com/16733681/164987630-1a658d6d-ac61-4e79-8ebc-dc392143e001.mp4
> Animate route list

- apps/admin-web/src/app/app.tsx
> Make filter case insensitive

- apps/admin-web/src/app/app.tsx
- apps/admin-web/src/app/components/Header.tsx
- libs/core/src/lib/__tests__/admin-endpoints.spec.ts
- libs/core/src/lib/admin.ts
- libs/core/src/lib/core.ts
- tsconfig.base.json
> Link to github from mezzo nav bar and list version in footer

- apps/admin-web/src/app/components/VariantButton.tsx
> Fix leading double slash on web fetch to api

- apps/admin-web/project.json
> Fix bug Cannot GET /site.webmanifest on main website

- apps/admin-web/src/app/hooks/useFilterFromURL.ts
- libs/core/package.json
Url was incorrect during typing in prod build
> Fix filter in prod

- README.md
- libs/core/src/lib/admin.ts
- libs/core/src/lib/core.ts
> Fix webmanifest 404 in prod build

- apps/admin-web/src/app/app.tsx
- apps/admin-web/src/app/components/RouteItem.tsx
> Use active variant from API as initial variant state

- README.md
- libs/interceptor-react-native-with-reactotron/README.md
- Updates our docs 
- updates lock file
- running npm i updated out lock file
> Update documentation and lock file

- apps/admin-web/src/app/components/SelectedNetworkItem.tsx
Element was showing as a pure string. Wrapped with a pre-tag and modfied the JSON.stringify() for better formatting.
> Add pre element around Strigified JSON

- apps/admin-web/proxy.conf.json
/api/food/meat and other endpoins would not load due to proxy/CORS issues
> fix(dev admin-web): fix proxy from 4200 react web to 8000 express

- apps/admin-web/src/app/components/HomeScreen.tsx
- apps/admin-web/src/app/components/Profiles/ProfilesScreen.tsx
- apps/admin-web/src/app/components/RecordScreen.tsx
- apps/admin-web/src/main.tsx
- Add MUI Theme Provider wrapper
- Update Styling for Profile Page
- Update Background Color and Button Color for other Pages
Closes #109
> feat: add theme provided update admin page styling

- apps/admin-web/src/app/app.css
- apps/admin-web/src/app/components/Header.tsx
- apps/admin-web/src/app/components/HomeScreen.tsx
- apps/admin-web/src/app/components/NetworkItem.tsx
- apps/admin-web/src/app/components/Profiles/ProfileButton.tsx
- apps/admin-web/src/app/components/Profiles/ProfileDetails.tsx
- apps/admin-web/src/app/components/Profiles/ProfilesScreen.tsx
- apps/admin-web/src/app/components/Profiles/SaveAsRemote.tsx
- apps/admin-web/src/app/components/RecordScreen.tsx
- apps/admin-web/src/app/components/RouteItem.tsx
- apps/admin-web/src/app/components/SelectedNetworkItem.tsx
- apps/admin-web/src/app/hooks/useRecordingClient.ts
- apps/admin-web/src/main.tsx
- Add Sticker header for better navigation on long scroll screens
- theme change to full dark mode to reduce background color styling - prep for better theming
- Start of Recording Screen styling - Added tables for items and split pane menu
- Network Toast removal
> feat: client refactoring and styling

- apps/admin-web/src/app/app.spec.tsx
- apps/admin-web/src/app/app.tsx
- apps/admin-web/src/app/components/Header.tsx
- apps/admin-web/src/app/components/HomeScreen.tsx
- apps/admin-web/src/app/hooks/useFetchInfo.ts
- apps/admin-web/src/app/hooks/useFetchRoutes.ts
- libs/core-client/src/lib/core-client.ts
- libs/core-client/src/lib/plugins/restClient.ts
- libs/core-server/src/index.ts
- libs/core-server/src/lib/core.ts
- libs/core-server/src/lib/plugins/routes-endpoints.ts
- libs/core-server/src/lib/plugins/server-info-endpoints.ts
- libs/interfaces/src/lib/dataInterfaces.ts
web frontend reflects if record & profile plugins are not enabled
Closes #146
> feat: suppress record & profiles if disabled

- apps/admin-web/src/app/components/NetworkItem.tsx
- apps/admin-web/src/app/components/RecordScreen.tsx
> feat: highlight selected network item on click

- .gitignore
- package-lock.json
- package.json
Attempting to resolve some security blockers by updating some of the dependencies.
> chore(deps): npm audit and update express
